### PR TITLE
Component doc fixes

### PR DESCRIPTION
**Pull request by richardpenner**
- Vanilla JS example in Banner docs has syntax errors

### CODE REVIEW

**Comment by alanthai** [comment]
I'm doing a PR here for docs https://github.com/Shopify/app-extension-libs/pull/788. I'm wondering whether we're treating this or the libs repo as source of truth (ie, PR to which repo needs to merge before first before moving to the other so that we don't experience conflicts)

**Comment by richardpenner** [comment]
No strong opinions from me. My changes here are all pretty simple so I'm happy to sort through some conflicts.

**Comment by dave-pelletier** [comment]
@richardpenner Do we still need this?

**Comment by richardpenner** [comment]
Whoa, I thought this was merged. This fixes syntax errors in our sample code so unless we happened to do that elsewhere, I think we should merge it.

**Comment by dave-pelletier** [comment]
This one was really old so I made a new branch with my rebase: https://github.com/Shopify/argo-admin-template/pull/76

**Pull request closed without merging**
