### PR TITLE
chore: upgrade-argo-admin-0.4.4

### PR DESCRIPTION
**Pull request by alanthai**
Related to: https://github.com/Shopify/argo-admin-cli/pull/19

Tickets:
https://github.com/Shopify/app-extension-libs/issues/790
https://github.com/Shopify/app-extension-libs/issues/791
https://github.com/Shopify/app-extension-libs/issues/793
https://github.com/Shopify/app-extension-libs/issues/794
https://github.com/Shopify/app-extension-libs/issues/830

## 🎩 instructions

1. [Tophat instructions](https://github.com/Shopify/app-extension-libs/wiki/Test-argo-admin-cli-changes#-tophat-instructions) and additionally change `argo-admin` to alpha as well.

    ```diff
    "devDependencies": {
    -    "@shopify/argo-admin-cli": "latest",
    +    "@shopify/argo-admin-cli": "git+https://github.com/Shopify/argo-admin-cli.git#chore/upgrade-argo-admin-0.4.4-test"
    },

    "dependencies": {
    -    "@shopify/argo-admin": "latest",
    -    "@shopify/argo-admin-host": "latest",
    +    "@shopify/argo-admin": "0.4.4-alpha.1",
    +    "@shopify/argo-admin-host": "0.4.4-alpha.1",
    },
    ```

1. Check that the buttons primary and secondary buttons are working (closing the modal)

### CODE REVIEW

**Review by henrytao-me — APPROVED** [review]
🎩-ed. LGTM

**Review by vividviolet — COMMENTED** [review]
Looks great - can you copy over the updated docs?

**Review by vividviolet — APPROVED** [review]
Code changes are 👍

**Review by vividviolet — APPROVED** [review]
Tophat'd

**Pull request merged**
