### PR TITLE
Add session token to react typescript template

### PR DESCRIPTION
**Pull request by henrytao-me**
Update react typescript to have session token

Resolves https://github.com/Shopify/app-extension-libs/issues/782

Added UI 

image

### CODE REVIEW

**Comment by henrytao-me** [comment]
I realize I still need to update the host to have sessionToken TextField

**Comment by dave-pelletier** [comment]
I get this error when I click the "Create plan" button in the modal:
```
messenger.js:157 Uncaught (in promise) 
{name: "ReferenceError", message: "getSessionToken is not defined", stack: "ReferenceError: getSessionToken is not defined↵   …http://0.0.0.0:39351/extension.worker.js:4597:29)"}
message: "getSessionToken is not defined"
name: "ReferenceError"
```

**Comment by henrytao-me** [comment]
> That's just so that partners can see it in the simulator UI right?

Right. Okay. I can skip the UI part but the host needs to be fixed. I will push it shortly.

**Comment by henrytao-me** [comment]
Added UI 

image

**Comment by henrytao-me** [comment]
Ready for reviewing 🙇

**Comment by dave-pelletier** [comment]
🎩 ✅

**Comment by iainmcampbell** [comment]
@vividviolet I remember we had a discussion about session token in the simulator and agreed it would just be blank/null?

**Comment by vividviolet** [comment]
Yeah, I guess if we let them specify the value they can set it to a mock that makes sense? I'm fine with either making it blank or blank by default and then letting them set a custom value. We should remove the existing token as it's actual token for an app.

**Comment by henrytao-me** [comment]
I was thinking if we just leave sessionToken blank / null in the host, developer might have a hard time to find where to override it. So, might be we just provide TextField for it.

**Pull request merged**
